### ISSUE TITLE
Добавить поддержку typescript

### ISSUE THREAD

**Issue by polRk** [VKCOM/create-vk-mini-app#13]

**Comment by S7rizh** [comment]
As I understood, there is still no TypeScript support yet. If someone is looking for a basic TS support that "just works" then check out this [fork](https://github.com/S7rizh/create-vk-mini-app). I am new to JS/TS/React and I am not pretending that everything is done correctly.

Also, it would be nice if the [quick start guide](https://vk.com/@vkappsdev-quick-start) will tell from the beginning that the option `HTTPS=true` should be removed to get rid of 502 responses while using ngrock :)
