### ISSUE TITLE
Не работает стартовое приложение

### ISSUE THREAD

**Issue by mlshv** [VKCOM/create-vk-mini-app#14]
Делаю всё, что указано здесь: https://vk.com/@vkappsdev-quick-start

Промис `connect.sendPromise('VKWebAppGetUserInfo')` не реджектится и не резолвится. В консоли не вижу ошибок, в Network не вижу запросов.

```js
try {
     console.log('fetchData'); // выводится
    const user = await connect.sendPromise('VKWebAppGetUserInfo');
    console.log('fetchData ok', user); // не выводится
    setUser(user);
    setPopout(null);
} catch (err) {
    console.log('fetchData err', err); // не выводится
}
```
Что я не так делаю?

**Comment by kuhel** [comment]
Можно хотя бы ссылку на код или прилу

**Comment by TemaSM** [comment]
@mlshv вероятнее всего `await connect.sendPromise('VKWebAppGetUserInfo')` выполнятся не внутри `async` функции, поэтому исполнение кода моментально  прекращается на этом моменте
