### ISSUE TITLE
[Bug]: Ошибка в README.md

### ISSUE THREAD

**Issue by jw-42** [VKCOM/create-vk-mini-app#170]
### Описание

В разделе «**Примеры командной строки**» во втором примере название шаблона, судя по описанию, должно быть «--template=**vkui-bridge**».

### Версия create-vk-mini-app

latest

### Платформа

Web

### Шаги воспроизведения

1. Открыть README.md

### Ожидаемое поведение

Во втором примере указана следующая  команда:
`npm init  @vkontakte/vk-mini-app . -- --template=vkui-bridge`

**Comment by pavel-nikitin-2022** [comment]
Добрый день, спасибо за обращение, поправим.
