### ISSUE TITLE
NPM repository has obsolete and non working version. 

### ISSUE THREAD

**Issue by stokito** [VKCOM/create-vk-mini-app#28]
Please perform a new release to NPM. I used this app with `npx @vkontakte/create-vk-mini-app` but got bunch of error like 

    ./src/panels/Persik.js
    Attempted import error: 'HeaderButton' is not exported from '@vkontakte/vkui'.

and `ListItem is not imported` (it was replaced with Cell) etc. I'm new to react and vkui and spent some time to figure out how to fix that.
P.S. Please add a link to this generator into VKUI documentation because now it's totally unclear how to use it for beginners like me. Thank you

**Comment by ilyapishchulin** [comment]
Replaced imports. Thank you
