### ISSUE TITLE
Can't resolve '@vkontakte/icons' in

### ISSUE THREAD

**Issue by paragulgov** [VKCOM/create-vk-mini-app#35]
Прописал 
`npx @vkontakte/create-vk-mini-app <folder name> `
`npm start`
как написано в документации, но вышла ошибка **Can't resolve '@vkontakte/icons' in ...**

Обновил иконки руками `(npm i @vkontakte/icons)` и **ЗАРАБОТАЛО.**

Исправьте пожалуйста.

**Comment by nodenwwsfww** [comment]
Поднимаю проблему, please, fix it.

**Comment by ilyapishchulin** [comment]
Исправили, спасибо
