### ISSUE TITLE
Error: Command failed: cd mini-app && npm install cross-env

### ISSUE THREAD

**Issue by Keller18306** [VKCOM/create-vk-mini-app#42]
C:\OpenServer\domains\justpro.local\CLI\nodejs\flappy_bird>npx @vkontakte/create-vk-mini-app

� Creating project...
⏱ Installing project dependencies — it might take a few minutes..
� npm error:
Error: Command failed: cd mini-app && npm install cross-env@^5.2.0 react-hot-loader@^4.9.0 react-scripts@^4.0.1 --save-dev && npm install @vkontakte/icons@^1.18.2 @vkontakte/vk-miniapps-deploy@^0.0.17 @vkontakte/vkui@4.0.4 babel-eslint@10.1.0 chalk@^2.4.2 eruda@^2.2.0 eruda-code@^2.0.0 eruda-dom@^2.0.0  prop-types@^15.7.2 react@^16.9.0 react-dom@^16.9.0 @vkontakte/vk-bridge@latest @vkontakte/vkjs@latest
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mini-app@1.0.0
npm ERR! Found: @vkontakte/icons@1.18.2
npm ERR! node_modules/@vkontakte/icons
npm ERR!   @vkontakte/icons@"1.18.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @vkontakte/icons@"^1.64.0" from @vkontakte/vkui@4.0.4
npm ERR! node_modules/@vkontakte/vkui
npm ERR!   @vkontakte/vkui@"4.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\kelle\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kelle\AppData\Local\npm-cache\_logs\2021-03-18T20_06_57_767Z-debug.log

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/111691286-377a2100-883f-11eb-941e-fa4ff5de5c30.png)

**Comment by Warale** [comment]
Столкнулся с такой же проблемой.

**Comment by ZixxanGames** [comment]
Try install LTS version of Node.js (v14.16.0)

**Comment by ilyapishchulin** [comment]
Проверите?

**Comment by Keller18306** [comment]
> Исправили. Проверите?

![image](https://user-images.githubusercontent.com/23178771/115398788-2e8abf80-a1f0-11eb-832f-ee76e54fc26b.png)

**Comment by ximik753** [comment]
> Исправили. Проверите?

Проблема всё ещё есть

**Comment by emilqw** [comment]
Понизьте версию npm до 6.14.11 с помощью команды `npm i npm@6.14.11 -g` и попробуйте снова. Все должно заработать.

**Comment by emilqw** [comment]
Понизьте версию npm до 6.14.11 с помощью команды `npm i npm@6.14.11 -g` и попробуйте снова. Все должно заработать.

**Comment by vadim-not2x** [comment]
> Понизьте версию npm до 6.14.11 с помощью команды `npm i npm@6.14.11 -g` и попробуйте снова. Все должно заработать.

![image](https://user-images.githubusercontent.com/76495024/120893445-0a5a3500-c61c-11eb-9583-155391823254.png)

**Comment by Thavguard** [comment]
у меня такая же проблема
![image](https://user-images.githubusercontent.com/89592313/147926330-fb6c1ea3-bf97-47b8-b00d-cd4112e631c4.png)

**Comment by ilyapishchulin** [comment]
Исправили, проверите?
