### ISSUE TITLE
Error: Command failed: cd mini-app && npm install cross-env@^7.0....

### ISSUE THREAD

**Issue by fialkovod** [VKCOM/create-vk-mini-app#49]
# create-vk-mini-app
🎬 Creating project...
⏱ Installing project dependencies — it might take a few minutes..
😳 npm error:
Error: Command failed: cd mini-app && npm install cross-env@^7.0.3 react-hot-loader@^4.13.0 react-scripts@^4.0.3 --save-dev && npm install @vkontakte/icons@^1.92.0 @vkontakte/vk-miniapps-deploy@0.0.25 @vkontakte/vkui@^4.5.0 babel-eslint@^10.1.0 chalk@^4.1.0 eruda@^2.4.1 eruda-code@^2.0.0 eruda-dom@^2.0.0  prop-types@^15.7.2 react@^17.0.2 react-dom@^17.0.2 @vkontakte/vk-bridge@latest @vkontakte/vkjs@latest
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mini-app@1.0.0
npm ERR! Found: @vkontakte/vkjs@0.21.0
npm ERR! node_modules/@vkontakte/vkjs
npm ERR!   @vkontakte/vkjs@"0.21.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @vkontakte/vkjs@"^0.20.0" from @vkontakte/vkui@4.7.0
npm ERR! node_modules/@vkontakte/vkui
npm ERR!   @vkontakte/vkui@"^4.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-20T20_41_04_064Z-debug.log

Проблема с указанием зависимостей, или что?

**Comment by peakle** [comment]
есть ли какие новости?)

**Comment by fialkovod** [comment]
Я забил. Проще руками поставить зависимости и потом скопировать шаблон. Там работы на пару минут.

**Comment by peakle** [comment]
я понизил версию npm до 6.14.11 и ноды до 16.1.0 и оно собралось : D
<img width="459" alt="Снимок экрана 2021-05-27 в 22 33 14" src="https://user-images.githubusercontent.com/27820873/119886341-87f6b480-bf3b-11eb-9948-8e8b28392bd8.png">

**Comment by emilqw** [comment]
Понизьте версию npm до 6.14.11 с помощью команды npm i npm@6.14.11 -gи попробуйте снова. Все должно заработать.

**Comment by emilqw** [comment]
Понизьте версию npm до 6.14.11 с помощью команды `npm i npm@6.14.11 -g` и попробуйте снова. Все должно заработать.

**Comment by ilyapishchulin** [comment]
Исправили, спасибо
