### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'mini-app/package.json'

### ISSUE THREAD

**Issue by tacitus-def** [VKCOM/create-vk-mini-app#57]
$ create-vk-mini-app 
🎬 Creating project...
⏱ Installing project dependencies — it might take a few minutes..
/home/demiurg/.config/yarn/global/node_modules/@vkontakte/create-vk-mini-app/bin/create-vk-mini-app.js:73
			if (err) throw err;
			         ^

[Error: ENOENT: no such file or directory, open 'mini-app/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'mini-app/package.json'
}

P.S. NodeJS: 16.13.2, OS: Ubuntu 20.04

**Comment by Lambo-555** [comment]
@tacitus-def try this
The same issue. Not all versions of NodeJS  work correctly.
Ununtu 21.10 - 64.

**Steps**:
Remove nodejs global
`sudo apt-get remove nodejs`

Install nodejs global, v12.22.5 (default). Do not update version
`sudo apt-get install nodejs`

Remove VK tool global. Use **yarn**
`yarn global remove @vkontakte/create-vk-mini-app`

Install  VK tool global
`yarn global add @vkontakte/create-vk-mini-app`

Run tool. Arguments not required
`create-vk-mini-app`

Success

**Comment by pavel-nikitin-2022** [comment]
Проблема исправлена в последней версии create-vk-mini-app
