### ISSUE TITLE
Невозможно создать шаблон мини-приложения

### ISSUE THREAD

**Issue by allexgorn** [VKCOM/create-vk-mini-app#58]
Здравствуйте! Пытаясь создать шаблон мини-приложения с помощью команды «npx @vkontakte/create-vk-mini-app название проекта» у меня появляется ошибка при установке зависимостей. Уже пытался понижать версию node и npm, но результат такой же. Я предполагаю, что проблема возникла со стороны разработчиков и надеюсь, что в ближайшее время они смогут решить данную проблему.

**Comment by ilyapishchulin** [comment]
Исправили, спасибо
