### ISSUE TITLE
The "vk bridge" library is not defined in the deployment on localhost and on the stage, prod version, but it is defined on the app_id

### ISSUE THREAD

**Issue by ogloblina-m** [VKCOM/create-vk-mini-app#76]
if you write in the console in prod, stage, or localhost versions :

```
bridge.send("VKWebAppInit");
Uncaught ReferenceError: bridge is not defined
    <anonymous> debugger eval code:1

```

**Comment by pasha-nikitin-2003** [comment]
You cannot call this code in the browser console, because the browser console does not know anything about the bridge library from your site's code and does not understand where to look for it.
