### ISSUE TITLE
Что дальше?

### ISSUE THREAD

**Issue by ibyteyou** [VKCOM/create-vk-mini-app#78]
<img width="768" alt="Снимок экрана 2022-07-20 в 02 06 30" src="https://user-images.githubusercontent.com/16253399/179862967-da7d10e9-d782-4b08-b1c3-a0b4537eeabd.png">

**Comment by ibyteyou** [comment]
<img width="1324" alt="Снимок экрана 2022-07-20 в 02 07 18" src="https://user-images.githubusercontent.com/16253399/179863048-a6e7207c-8e07-4ef1-b46e-6392b0b5a9e6.png">

**Comment by Zombie1995** [comment]
Посмотри, что в коде;)

**Comment by pasha-nikitin-2003** [comment]
Для работы необходимо создать мини приложение и встроить в него сайт, подробнее можно прочитать [здесь](https://dev.vk.com/ru/mini-apps/getting-started).
